# Generated by Django 3.0.5 on 2020-05-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total_Users',
        ),
    ]
