# Generated by Django 3.0.5 on 2020-05-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_delete_total_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userImage',
            new_name='profile_pic',
        ),
    ]
